apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector: #pods which deployment has to manage
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: zura123490/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret #secret key object
                  key: JWT_KEY #selecting key from key objec (as it can contain multiple keys)
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector: # it will look for pod with name of auth (e.g metadata:labels:app:auth)
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
